{
 "title": "Pars bot service monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Время затраченное ботом на подключение к веб-сайту и загрузку веб-страницы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "crawler_site_connection_time_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество обработанных ботом страниц",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    { "expr": "crawler_pages_parsed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время затраченное ботом на обработку содержимого веб-страницы",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    { "expr": "crawler_page_parse_time_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время генерации веб-страниц, учитывая время обработки запроса",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "targets": [
    { "expr": "web_page_gen_time_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество обработанных запросов",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "web_pages_served", "legendFormat": "__auto" }
   ]
  }
 ]
}